### ISSUE TITLE
Make raven_change_path accessible to the outside world on GCP

### ISSUE THREAD

**Issue by bs** [earthspecies/raven_change_path#2]
Likely: https://tools.earthspecies.org/raven

**Comment by bs** [comment]
[Done!](https://tools.earthspecies.org/raven)

Was a bit more involved than I anticipated. In particular:

1. I had hoped to simply bootstrap off of @radekosmulski existing 1-liner cron job. We can’t do that for a couple of reasons:

- Currently it’s executing ```/opt/local/bin/conda jupyter notebook```
- This means there’s the potential for arbitrary code execution
- It needs to run as root to serve port 80 ... even worse!

Luckily, Voila includes a way to easily spin up a [Tornado](https://www.tornadoweb.org/en/stable/) server, as well as run in a sandbox that prevents any notebook/Python shenanigans. They also [have great documentation](https://voila.readthedocs.io/en/stable/deploy.html)!

2. SSL, Routing

And we want the url to be /raven or some such, and besides, Tornado’s not really suited for serving SSL certs, routing, etc. This means nginx and proxy_pass. LetsEncrypt for the cert and we’re done!

**Comment by radekosmulski** [comment]
w00t! 😄 this is great stuff right here - awesome find on the docs, really nice of the voila people to provide that functionality for serving

seems neither the nice URL
![image](https://user-images.githubusercontent.com/2444926/83024089-20f3a680-a02e-11ea-9e97-d1f77f944091.png)

nor the earlier version 
![image](https://user-images.githubusercontent.com/2444926/83024142-3668d080-a02e-11ea-87fe-b1c331abe439.png)

work now - paging Dr. Britt to the ER 😁

**Comment by bs** [comment]
Hmm ... something strange is going on. It's not resolving on all of my browsers EXCEPT Firefox on my dev machine that I was testing on ... I thought maybe it was aggressively caching but it doesn't look like it. Looking into it now.

The old one isn't running, so that's expected. But as the new one isn't either I'll toss it back up and then make a redirect to the new page once this is fixed.

**Comment by bs** [comment]
This should be fixed. Please confirm and I'll close.

I also set up a ```301 redirect``` from the IP address at ```http://35.203.129.79:8888/voila/render/modify_path.ipynb```, for anyone who is using it.

The only case I can find that breaks is when using the [HTTPS Everywhere Plugin](https://www.eff.org/https-everywhere) on Firefox. Nothing we can do about this, really. It intercepts the request and redirects it to ```https://35.203.129.8888```, which of course we can't serve without the browser calling foul.

Fun fact/extra reading: It's [technically possible](https://stackoverflow.com/questions/2043617/is-it-possible-to-have-ssl-certificate-for-ip-address-not-domain-name) to certify an IP address, but [not supported by LetsEncrypt](https://community.letsencrypt.org/t/certificate-for-public-ip-without-domain-name/6082/91).

**Comment by radekosmulski** [comment]
yay! works like a charm! 😊 kudos on the depth of analysis in sorting this out!
